name: Build_Linux_aarch64

on:
  workflow_call:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    env:
      SONAR_SCANNER_VERSION: 4.7.0.2747
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: ${{github.workspace}}/wrapper


    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu-latest

      - name: boost
        run: |
          sudo apt-get install libboost-all-dev

      - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: |
          export CC=/usr/bin/gcc-10
          export CXX=/usr/bin/g++-10
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Run build
        run: |
          export CC=/usr/bin/gcc-10
          export CXX=/usr/bin/g++-10
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Prepare artifacts
        run: |
          mkdir -p ${{github.workspace}}/build/x64
          mv ${{github.workspace}}/build/R.A.B.I.D.S ${{github.workspace}}/build/x64/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: R.A.B.I.D.S_x64
          path: ${{github.workspace}}/build/x64
          retention-days: 0
          
        
        
