name: Release

on:
  push:
    tags:
      - "v**.**.**"
  workflow_dispatch:

jobs:
  x64:
    uses: ./.github/workflows/x64.yml

  release:
    needs: [x64]
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yaml
