name: release.builder
on:
  workflow_call:

jobs:
  release:
    name: Make release draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: develop

      - name: Make download folder
        run: mkdir artifacts 
      
      - name: Download artifacts
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          path: ./artifacts/


      - name: Build x64 deploy archive
        uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
        with:
          files: ./artifacts\R.A.B.I.D.S_x64\
          dest: ./R.A.B.I.D.S-x64.zip

      - name: Upload x64 deploy archive
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: R.A.B.I.D.S-x64.zip
          path: ./R.A.B.I.D.S-x64.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Draft commit created by workflow
            ### put data here
          draft: true
          prerelease: false

      - name: Upload R.A.B.I.D.S-x64.zip
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./R.A.B.I.D.S-x64.zip
          asset_name: R.A.B.I.D.S-x64.zip
          asset_content_type: application/zip   