name: Build_Linux_x64

on:
  workflow_call:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          fetch-depth: 0

      - name: boost
        run: |
          sudo apt-get install libboost-all-dev

      - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: |
          export CC=/usr/bin/gcc-10
          export CXX=/usr/bin/g++-10
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          gcc --version
          export CC=/usr/bin/gcc-10
          export CXX=/usr/bin/g++-10
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
      - name: Prepare artifacts
        run: |
          mkdir -p ${{github.workspace}}/build/x64
          mv ${{github.workspace}}/build/R.A.B.I.D.S ${{github.workspace}}/build/x64/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: R.A.B.I.D.S_x64
          path: ${{github.workspace}}/build/x64
          retention-days: 0
          
        
        
