name: Build_Linux_x64

on:
  workflow_call:

env:
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          fetch-depth: 0

      - name: boost
        run: |
          sudo apt-get install libboost-all-dev

      - name: Configure CMake
        run: |
          export CC=/usr/bin/gcc-10
          export CXX=/usr/bin/g++-10
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          gcc --version
          export CC=/usr/bin/gcc-10
          export CXX=/usr/bin/g++-10
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Prepare artifacts
        run: |
          mkdir -p ${{github.workspace}}/build/x64
          mv ${{github.workspace}}/build/R.A.B.I.D.S ${{github.workspace}}/build/x64/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: R.A.B.I.D.S_x64
          path: ${{github.workspace}}/build/x64
          retention-days: 0
